default:
  image: gradle:6-jdk11-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - gradle bootJar --warning-mode all
  artifacts:
    paths:
      - build\libs\bookworm-backend-0.0.1-SNAPSHOT.jar
    expire_in: 1 hour

test-job:
  stage: test
  image: docker/compose:alpine-1.29.2
  script:
    - cd docker || { echo "Docker folder does not exist."; exit 1; }
    - ln ../build/libs/bookworm-backend-0.0.1-SNAPSHOT.jar ./bookworm_backend/bookworm-backend-0.0.1-SNAPSHOT.jar
    - docker-compose up -d
    - cd .. && gradle check && cd docker
    - docker-compose down
    - unlink ./bookworm_backend/bookworm-backend-0.0.1-SNAPSHOT.jar
  artifacts:
    paths:
      - build/karate-reports/*
    expire_in: 1 hour
