# needs metrics enabled (actuator access) to work
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    io.kompose.network/bookworm-network: "true"
  name: bookworm-backend-hpa
  namespace: bookworm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bookworm-backend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
