# keycloak
keycloak.url=http://localhost:8080
# database
spring.datasource.url=jdbc:postgresql://localhost:5432/bookworm_library
# redis cache
spring.redis.host=localhost
# spring cloud config
spring.config.import=optional:configserver:
spring.cloud.config.enabled=false
